eval `dbus-launch --auto-syntax`

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge ~/.Xresources

export DESKTOP_SESSION=plasma
export KDEWM=/usr/bin/i3
exec startplasma-x11 > ~/.Xorg.log 2>&1
