xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

eval `dbus-launch --auto-syntax`

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge ~/.Xresources

export DESKTOP_SESSION=plasma
export KDEWM=/usr/bin/i3
startplasma-x11
