source "$HOME/.local/lib/zsh/oh-my-zsh.sh"
source "$HOME/.local/lib/zsh/keyboard.sh"

# Aliases
alias ipython='ipython --no-banner --no-confirm-exit'
alias ls='lsd'
alias rtv='rtv --enable-media'
alias tree='lsd --tree'
alias xp='xclip -selection p'
alias xpo='xclip -selection p -o'

HISTSIZE="65536"
SAVEHIST="65536"
HISTFILE="$HOME/.histfile"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY
setopt autocd

autoload -Uz promptinit && promptinit
function custom_prompt() {
  echo "$CUSTOM_PS1"
}

CUSTOM_PS1='> '
PROMPT="%{$fg[magenta]%}%n%{$reset_color%}@%{$fg[yellow]%}%m%{$reset_color%} %{$fg_bold[green]%}%~%{$reset_color%} $(git_prompt_info)"$'\n'"$(custom_prompt)"

# Don't stop output on ^S
stty stop undef
stty start undef

eval "$(fasd --init auto)"
eval "$(direnv hook zsh)"
