# {{ antigen
source "$HOME/.local/lib/zsh/antigen/antigen.zsh"
antigen use 'oh-my-zsh'
antigen bundle 'cargo'
antigen bundle 'colorize'
antigen bundle 'docker'
antigen bundle 'kubectl'
antigen bundle 'pass'
antigen bundle 'git'
antigen bundle 'gpg-agent'
antigen bundle 'zsh_reload'

antigen bundle 'zsh-users/zsh-syntax-highlighting'
antigen bundle 'zsh-users/zsh-autosuggestions'
antigen bundle 'zsh-users/zsh-completions'

antigen bundle 'NullSense/fuzzy-sys'
antigen bundle 'wfxr/forgit'

antigen apply
# }}

# TODO configure PATH with jsonnet
export PATH="$HOME/.cargo/bin:$PATH"

if command -v bat &> /dev/null; then
  # Color man using bat
  export MANPAGER="sh -c 'col -bx | bat -l man -p --paging always'"
fi

# Aliases
# TODO configure aliases with jsonnet
alias ipython='ipython --no-banner --no-confirm-exit'
alias ls='lsd'
alias rtv='rtv --enable-media'
alias tree='lsd --tree'
alias xp='xclip -selection p'
alias xpo='xclip -selection p -o'

HISTSIZE="65536"
SAVEHIST="65536"
HISTFILE="$HOME/.histfile"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY
setopt autocd

autoload -Uz promptinit && promptinit
function custom_prompt() {
  echo "$CUSTOM_PS1"
}

CUSTOM_PS1='> '
PROMPT="%{$fg[magenta]%}%n%{$reset_color%}@%{$fg[yellow]%}%m%{$reset_color%} %{$fg_bold[green]%}%~%{$reset_color%} $(git_prompt_info)"$'\n'"$(custom_prompt)"

# Don't stop output on ^S
stty stop undef
stty start undef

source "$HOME/.local/lib/zsh/keyboard.sh"

# TODO modularize...
# {{ fzf
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

function fman() {
  man -k . \
    | fzf -q "$1" \
    --prompt='man> ' \
    --preview $'echo {} | tr -d \'()\' | awk \'{printf "%s ", $2} {print $1}\' | xargs -r man | col -bx | bat -l man -p --color always' \
    | tr -d '()' \
    | awk '{printf "%s ", $2} {print $1}' \
    | xargs -r man
}
function fgco() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)")
  branch=$(echo "$branches" | fzf -d $(( 2 + $(wc -l <<< "$branches") )) +m)
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

_fzf_compgen_path() {
  $FZF_DEFAULT_COMMAND . "$1"
}

_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# }}

eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

source "$HOME/.config/nvm/nvm.sh"
