# TODO: add flavours update to topgrade
# TODO: make this more modular
shell = "bash -c '{}'"

[[item]]
file = "~/.config/nvim/colors/base16.vim"
template = "vim"
rewrite = true
hook = "~/.local/lib/flavour/nvim.sh"

[[item]]
file = "~/.config/bat/themes/my-base16.tmTheme"
template = "textmate"
rewrite = true
hook = "bat cache --build"

[[item]]
file = "~/.config/alacritty/alacritty.yml"
template = "alacritty"
subtemplate = "default-256"
rewrite = true

[[item]]
file = "~/.Xresources"
template = "xresources"
rewrite = true
hook = "xrdb -merge ~/.Xresources"
